apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: zkzu9jkrm-python 
  janus-idp.io/tekton: zkzu9jkrm-python
  backstage.io/kubernetes-id: zkzu9jkrm-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zkzu9jkrm-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  