apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: zkzu9jkrm-python-gitops
  description: This is GitOps manifest for zkzu9jkrm-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: zkzu9jkrm-python
    backstage.io/kubernetes-id: zkzu9jkrm-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: zkzu9jkrm-python   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:zkzu9jkrm-python
